import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL = 'https://fjysngoakqbemhjyfima.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_dIs-fsCy5wKEdFyDbf7Geg_2kZw_4Cp';
const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

const app = document.querySelector('#app');
const toastRoot = document.querySelector('#toast-root');
const brl = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const monthFmt = new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' });
const state = { session:null, profile:null, household:null, selectedMonth:firstDayISO(new Date()), activeTab:'home', transactions:[], boxes:[], boxBalances:[], goals:[], monthlySummary:[], loading:true };
const icons = { home:'⌂', transactions:'↕', boxes:'▣', reports:'▥', goals:'◎' };

function firstDayISO(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-01`}
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(v){return brl.format(Number(v||0))}
function monthLabel(iso){return monthFmt.format(new Date(`${iso}T12:00:00`))}
function toast(message,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;toastRoot.appendChild(el);setTimeout(()=>el.remove(),3200)}
function authName(){return state.profile?.display_name||state.session?.user?.email?.split('@')[0]||'JuHelo'}
function initials(name){return (name||'JH').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'JH'}
function pct(v,t){return !t?0:Math.max(0,Math.min(100,Math.round((Number(v)/Number(t))*100)))}

function topbar(){return `<header class="topbar"><div class="brand-inline"><div class="mini-logo">♡</div><div><span style="color:var(--purple)">Ju</span>Helo</div></div><div class="user-chip"><span>${esc(authName())}</span><div class="avatar">${esc(initials(authName()))}</div></div></header>`}
function nav(){return `<nav class="bottom-nav">${[['home','Início'],['transactions','Movimentações'],['boxes','Caixinhas'],['reports','Relatórios'],['goals','Metas']].map(([id,label])=>`<button class="nav-item ${state.activeTab===id?'active':''}" data-tab="${id}"><span class="nav-icon">${icons[id]}</span><span>${label}</span></button>`).join('')}</nav>`}
function render(){if(state.loading)return renderSplash();if(!state.session)return renderAuth();if(!state.household)return renderOnboarding();renderApp()}
function renderSplash(){app.innerHTML=`<div class="splash"><div class="brand-mark">♡</div><div class="brand-name"><span>Ju</span>Helo</div><p>finanças do casal</p></div>`}

function renderAuth(mode='login'){
 const signup=mode==='signup';
 app.innerHTML=`<main class="page narrow"><div class="topbar"><div class="brand-inline"><div class="mini-logo">♡</div><div><span style="color:var(--purple)">Ju</span>Helo</div></div></div><section class="auth-card"><h1>${signup?'Criar sua conta':'Entrar no JuHelo'}</h1><p>${signup?'Depois você cria ou entra no espaço financeiro do casal.':'Suas finanças do casal em um lugar simples.'}</p><form id="auth-form" class="form-grid">${signup?'<div class="field"><label>Seu nome</label><input class="input" name="name" required></div>':''}<div class="field"><label>E-mail</label><input class="input" type="email" name="email" required></div><div class="field"><label>Senha</label><input class="input" type="password" name="password" minlength="6" required></div><button class="btn primary block">${signup?'Criar conta':'Entrar'}</button></form><div class="auth-switch">${signup?'Já tem uma conta?':'Ainda não tem conta?'} <button class="link-btn" id="switch-auth">${signup?'Entrar':'Criar conta'}</button></div></section></main>`;
 document.querySelector('#switch-auth').onclick=()=>renderAuth(signup?'login':'signup');
 document.querySelector('#auth-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{if(signup){const {error}=await supabase.auth.signUp({email:fd.get('email').trim(),password:fd.get('password'),options:{data:{display_name:fd.get('name').trim()}}});if(error)throw error;toast('Conta criada. Confira o e-mail se a confirmação estiver ativa.')}else{const {error}=await supabase.auth.signInWithPassword({email:fd.get('email').trim(),password:fd.get('password')});if(error)throw error}}catch(err){toast(err.message||'Falha na autenticação.','error')}};
}

function renderOnboarding(){
 app.innerHTML=`<main class="page narrow">${topbar()}<section class="auth-card"><div class="brand-mark" style="width:58px;height:58px;font-size:36px;margin:0 0 18px">♡</div><h1>Nosso dinheiro</h1><p>Crie o JuHelo de vocês ou entre usando o código de convite do parceiro.</p><div class="form-grid"><button class="btn primary" id="create-household">Criar nosso JuHelo</button><div style="display:flex;align-items:center;gap:12px;color:var(--muted)"><span style="height:1px;background:var(--line);flex:1"></span>ou<span style="height:1px;background:var(--line);flex:1"></span></div><div class="field"><label>Código do parceiro</label><input id="invite-code" class="input" placeholder="Ex.: A1B2C3D4"></div><button class="btn soft" id="join-household">Entrar com código</button></div></section></main>`;
 document.querySelector('#create-household').onclick=async()=>{const {error}=await supabase.rpc('create_household',{p_name:'JuHelo'});if(error)return toast(error.message,'error');await loadAll();toast('JuHelo criado 💜')};
 document.querySelector('#join-household').onclick=async()=>{const code=document.querySelector('#invite-code').value.trim();if(!code)return toast('Digite o código.','error');const {error}=await supabase.rpc('join_household',{p_invite_code:code});if(error)return toast(error.message,'error');await loadAll();toast('Você entrou no JuHelo 💜')};
}

function monthSelect(){const base=new Date(`${state.selectedMonth}T12:00:00`);let out='';for(let i=-12;i<=12;i++){const d=new Date(base.getFullYear(),base.getMonth()+i,1),iso=firstDayISO(d);out+=`<option value="${iso}" ${iso===state.selectedMonth?'selected':''}>${esc(monthLabel(iso))}</option>`}return `<select class="month-select" id="month-select">${out}</select>`}
function currentTransactions(direction){return state.transactions.filter(t=>t.month===state.selectedMonth&&(!direction||t.direction===direction))}
function summary(){const income=currentTransactions('income').reduce((s,t)=>s+Number(t.amount),0),expense=currentTransactions('expense').reduce((s,t)=>s+Number(t.amount),0);return {income,expense,result:income-expense}}
function row(tx){const recurring=tx.kind==='recurring',box=tx.kind==='box_contribution';return `<div class="row"><div class="row-icon">${tx.direction==='income'?'↗':box?'▣':recurring?'↻':'↘'}</div><div class="row-main"><div class="row-title">${esc(tx.description)}</div><div class="row-sub">${box?'Caixinha':recurring?'Gasto fixo':tx.direction==='income'?'Receita':'Despesa'}</div></div><div class="row-value">${money(tx.amount)}</div><button class="icon-btn edit-tx" data-id="${tx.id}">✎</button></div>`}
function list(items){return items.length?`<div class="list">${items.map(row).join('')}</div>`:'<div class="empty">Nenhum lançamento neste mês.</div>'}

function home(){const s=summary();return `<section class="hero"><div class="hero-row"><div><div class="eyebrow">Saldo do mês</div><div class="balance">${money(s.result)}</div><div class="eyebrow">Receitas menos despesas</div></div>${monthSelect()}</div></section><div class="kpi-grid"><div class="kpi income"><div class="label">Receitas</div><div class="value">${money(s.income)}</div></div><div class="kpi expense"><div class="label">Despesas</div><div class="value">${money(s.expense)}</div></div><div class="kpi"><div class="label">Resultado do mês</div><div class="value">${money(s.result)}</div></div></div><div class="quick-actions"><button class="quick expense" data-action="new-expense">＋<small>Despesa</small></button><button class="quick income" data-action="new-income">＋<small>Receita</small></button><button class="quick box" data-action="box-add">＋<small>Caixinha</small></button><button class="quick goal" data-action="new-goal">＋<small>Meta</small></button></div><div class="grid-2"><section class="panel"><div class="panel-head"><h2>Despesas</h2><button class="link-btn" data-tab="transactions">Ver todas</button></div>${list(currentTransactions('expense').slice(0,5))}</section><section class="panel"><div class="panel-head"><h2>Receitas</h2><button class="link-btn" data-tab="transactions">Ver todas</button></div>${list(currentTransactions('income').slice(0,5))}</section></div>`}
function transactions(){const s=summary();return `<div class="section-title"><div><h1>Movimentações</h1><p>${esc(monthLabel(state.selectedMonth))}</p></div>${monthSelect()}</div><div class="quick-actions"><button class="quick expense" data-action="new-expense">＋<small>Despesa</small></button><button class="quick income" data-action="new-income">＋<small>Receita</small></button><button class="quick box" data-action="box-add">＋<small>Caixinha</small></button><button class="quick goal" data-action="new-recurring">↻<small>Gasto fixo</small></button></div><div class="kpi-grid"><div class="kpi income"><div class="label">Receitas</div><div class="value">${money(s.income)}</div></div><div class="kpi expense"><div class="label">Despesas</div><div class="value">${money(s.expense)}</div></div><div class="kpi"><div class="label">Saldo</div><div class="value">${money(s.result)}</div></div></div><section class="panel">${list(currentTransactions())}</section>`}
function boxes(){const balances=new Map(state.boxBalances.map(b=>[b.box_id,Number(b.balance)]));return `<div class="section-title"><div><h1>Caixinhas</h1><p>Dinheiro separado para os planos de vocês.</p></div><button class="btn soft" data-action="new-box">＋ Nova caixinha</button></div><div class="card-grid">${state.boxes.length?state.boxes.map(b=>{const balance=balances.get(b.id)||0,p=pct(balance,b.target_amount);return `<article class="box-card"><div class="box-top"><div><div class="box-name">${esc(b.name)}</div><span class="pill">${b.target_amount?`Meta ${money(b.target_amount)}`:'Sem meta definida'}</span></div></div><div class="box-balance">${money(balance)}</div><div class="row-sub">Saldo atual</div>${b.target_amount?`<div class="progress"><span style="width:${p}%"></span></div><div class="row-sub" style="margin-top:6px">${p}% da meta</div>`:''}<div class="actions-inline" style="margin-top:16px"><button class="btn soft add-box" data-id="${b.id}">Adicionar</button><button class="btn ghost withdraw-box" data-id="${b.id}">Retirar</button></div></article>`}).join(''):'<div class="panel empty">Crie a primeira caixinha de vocês.</div>'}</div>`}
function goals(){return `<div class="section-title"><div><h1>Metas</h1><p>Um checklist para os planos do casal.</p></div><button class="btn soft" data-action="new-goal">＋ Nova meta</button></div><section class="panel">${state.goals.length?state.goals.map(g=>`<div class="goal-row"><button class="check ${g.is_completed?'done':''}" data-goal="${g.id}">${g.is_completed?'✓':''}</button><div><div class="row-title">${esc(g.title)}</div><div class="row-sub">${g.target_amount?`Meta financeira: ${money(g.target_amount)}`:g.notes?esc(g.notes):'Checklist do casal'}</div></div><button class="icon-btn edit-goal" data-id="${g.id}">✎</button></div>`).join(''):'<div class="empty">Nenhuma meta criada ainda.</div>'}</section>`}
function reports(){const year=Number(state.selectedMonth.slice(0,4)),rows=state.monthlySummary.filter(x=>Number(String(x.month).slice(0,4))===year),income=rows.reduce((s,x)=>s+Number(x.total_income),0),expense=rows.reduce((s,x)=>s+Number(x.total_expense),0),max=Math.max(1,...rows.flatMap(x=>[Number(x.total_income),Number(x.total_expense)]));const bars=Array.from({length:12},(_,i)=>{const iso=`${year}-${String(i+1).padStart(2,'0')}-01`,r=rows.find(x=>x.month===iso)||{total_income:0,total_expense:0};return `<div class="chart-col"><div class="bar income" style="height:${Math.round(Number(r.total_income)/max*100)}%"></div><div class="bar expense" style="height:${Math.round(Number(r.total_expense)/max*100)}%"></div><span class="chart-label">${String(i+1).padStart(2,'0')}</span></div>`}).join('');return `<div class="section-title"><div><h1>Relatórios</h1><p>Visão anual do dinheiro de vocês.</p></div></div><div class="kpi-grid"><div class="kpi income"><div class="label">Receitas no ano</div><div class="value">${money(income)}</div></div><div class="kpi expense"><div class="label">Despesas no ano</div><div class="value">${money(expense)}</div></div><div class="kpi"><div class="label">Saldo acumulado</div><div class="value">${money(income-expense)}</div></div></div><section class="panel"><div class="panel-head"><div><h2>Receita x despesa</h2><div class="row-sub">Verde = receita · Rosa = despesa</div></div></div><div class="chart">${bars}</div></section>`}
function renderApp(){const content=state.activeTab==='home'?home():state.activeTab==='transactions'?transactions():state.activeTab==='boxes'?boxes():state.activeTab==='reports'?reports():goals();app.innerHTML=`<main class="page">${topbar()}${content}</main>${nav()}`;bind()}

function modal(title,body,onMount){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<section class="modal-card"><div class="modal-head"><h2>${esc(title)}</h2><button class="icon-btn" data-close>×</button></div>${body}</section>`;document.body.appendChild(wrap);wrap.querySelector('[data-close]').onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};onMount?.(wrap)}
function bind(){document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{state.activeTab=el.dataset.tab;render()});const month=document.querySelector('#month-select');if(month)month.onchange=async()=>{state.selectedMonth=month.value;await ensureRecurring();await loadTransactions();render()};document.querySelectorAll('[data-action="new-expense"]').forEach(el=>el.onclick=()=>openTx(null,'expense'));document.querySelectorAll('[data-action="new-income"]').forEach(el=>el.onclick=()=>openTx(null,'income'));document.querySelectorAll('[data-action="new-box"]').forEach(el=>el.onclick=openBox);document.querySelectorAll('[data-action="box-add"]').forEach(el=>el.onclick=()=>openBoxAdd());document.querySelectorAll('[data-action="new-goal"]').forEach(el=>el.onclick=()=>openGoal());document.querySelectorAll('[data-action="new-recurring"]').forEach(el=>el.onclick=openRecurring);document.querySelectorAll('.edit-tx').forEach(el=>el.onclick=()=>openTx(state.transactions.find(t=>t.id===el.dataset.id)));document.querySelectorAll('.add-box').forEach(el=>el.onclick=()=>openBoxAdd(el.dataset.id));document.querySelectorAll('.withdraw-box').forEach(el=>el.onclick=()=>openWithdraw(el.dataset.id));document.querySelectorAll('[data-goal]').forEach(el=>el.onclick=async()=>{const g=state.goals.find(x=>x.id===el.dataset.goal);const{error}=await supabase.from('goals').update({is_completed:!g.is_completed,completed_at:!g.is_completed?new Date().toISOString():null}).eq('id',g.id);if(error)return toast(error.message,'error');await loadGoals();render()});document.querySelectorAll('.edit-goal').forEach(el=>el.onclick=()=>openGoal(state.goals.find(g=>g.id===el.dataset.id)))}

function openTx(tx=null,preset='expense'){let dir=tx?.direction||preset;modal(tx?'Editar lançamento':dir==='income'?'Nova receita':'Nova despesa',`<form id="f" class="form-grid"><div class="segmented"><button type="button" data-dir="expense" class="${dir==='expense'?'active':''}">Despesa</button><button type="button" data-dir="income" class="${dir==='income'?'active':''}">Receita</button></div><div class="field"><label>Descrição</label><input class="input" name="description" value="${esc(tx?.description||'')}" required></div><div class="field"><label>Valor</label><input class="input" name="amount" type="number" step="0.01" min="0.01" value="${tx?.amount||''}" required></div><div class="field"><label>Mês</label><input class="input" name="month" type="month" value="${(tx?.month||state.selectedMonth).slice(0,7)}" required></div>${tx?'<button class="btn red" type="button" id="del">Excluir lançamento</button>':''}<div class="modal-actions"><button class="btn ghost" type="button" data-cancel>Cancelar</button><button class="btn primary">Salvar</button></div></form>`,w=>{w.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{dir=b.dataset.dir;w.querySelectorAll('[data-dir]').forEach(x=>x.classList.toggle('active',x===b))});w.querySelector('[data-cancel]').onclick=()=>w.remove();if(tx)w.querySelector('#del').onclick=async()=>{if(!confirm('Excluir este lançamento?'))return;const{error}=await supabase.from('transactions').delete().eq('id',tx.id);if(error)return toast(error.message,'error');w.remove();await refresh();render()};w.querySelector('#f').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),payload={household_id:state.household.id,direction:dir,kind:tx?.kind||'regular',description:fd.get('description').trim(),amount:Number(fd.get('amount')),month:`${fd.get('month')}-01`,updated_by:state.session.user.id};let error;if(tx)({error}=await supabase.from('transactions').update(payload).eq('id',tx.id));else({error}=await supabase.from('transactions').insert({...payload,created_by:state.session.user.id}));if(error)return toast(error.message,'error');w.remove();await refresh();render()}})}
function openBox(){modal('Nova caixinha','<form id="f" class="form-grid"><div class="field"><label>Nome</label><input class="input" name="name" required></div><div class="field"><label>Meta de valor (opcional)</label><input class="input" name="target" type="number" step="0.01" min="0.01"></div><div class="modal-actions"><button class="btn ghost" type="button" data-cancel>Cancelar</button><button class="btn primary">Criar</button></div></form>',w=>{w.querySelector('[data-cancel]').onclick=()=>w.remove();w.querySelector('#f').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),target=fd.get('target');const{error}=await supabase.from('boxes').insert({household_id:state.household.id,name:fd.get('name').trim(),target_amount:target?Number(target):null,created_by:state.session.user.id});if(error)return toast(error.message,'error');w.remove();await loadBoxes();render()}})}
function openBoxAdd(boxId=''){if(!state.boxes.length)return toast('Crie uma caixinha primeiro.','error');modal('Adicionar à caixinha',`<form id="f" class="form-grid"><div class="field"><label>Caixinha</label><select class="input" name="box">${state.boxes.map(b=>`<option value="${b.id}" ${b.id===boxId?'selected':''}>${esc(b.name)}</option>`).join('')}</select></div><div class="field"><label>Valor</label><input class="input" name="amount" type="number" step="0.01" min="0.01" required></div><div class="field"><label>Mês</label><input class="input" name="month" type="month" value="${state.selectedMonth.slice(0,7)}" required></div><div class="modal-actions"><button class="btn ghost" type="button" data-cancel>Cancelar</button><button class="btn primary">Adicionar</button></div></form>`,w=>{w.querySelector('[data-cancel]').onclick=()=>w.remove();w.querySelector('#f').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const{error}=await supabase.rpc('add_box_contribution',{p_box_id:fd.get('box'),p_amount:Number(fd.get('amount')),p_month:`${fd.get('month')}-01`,p_description:null});if(error)return toast(error.message,'error');w.remove();await refresh();render()}})}
function openWithdraw(boxId){modal('Retirar da caixinha',`<form id="f" class="form-grid"><div class="field"><label>Valor</label><input class="input" name="amount" type="number" step="0.01" min="0.01" required></div><div class="field"><label>Mês</label><input class="input" name="month" type="month" value="${state.selectedMonth.slice(0,7)}" required></div><div class="modal-actions"><button class="btn ghost" type="button" data-cancel>Cancelar</button><button class="btn primary">Retirar</button></div></form>`,w=>{w.querySelector('[data-cancel]').onclick=()=>w.remove();w.querySelector('#f').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const{error}=await supabase.rpc('withdraw_from_box',{p_box_id:boxId,p_amount:Number(fd.get('amount')),p_month:`${fd.get('month')}-01`,p_description:null});if(error)return toast(error.message,'error');w.remove();await loadBoxes();render()}})}
function openGoal(goal=null){modal(goal?'Editar meta':'Nova meta',`<form id="f" class="form-grid"><div class="field"><label>Meta</label><input class="input" name="title" value="${esc(goal?.title||'')}" required></div><div class="field"><label>Observação</label><input class="input" name="notes" value="${esc(goal?.notes||'')}"></div><div class="field"><label>Caixinha vinculada</label><select class="input" name="box"><option value="">Nenhuma</option>${state.boxes.map(b=>`<option value="${b.id}" ${goal?.box_id===b.id?'selected':''}>${esc(b.name)}</option>`).join('')}</select></div><div class="field"><label>Valor alvo</label><input class="input" name="target" type="number" step="0.01" min="0.01" value="${goal?.target_amount||''}"></div>${goal?'<button class="btn red" type="button" id="del">Excluir meta</button>':''}<div class="modal-actions"><button class="btn ghost" type="button" data-cancel>Cancelar</button><button class="btn primary">Salvar</button></div></form>`,w=>{w.querySelector('[data-cancel]').onclick=()=>w.remove();if(goal)w.querySelector('#del').onclick=async()=>{const{error}=await supabase.from('goals').delete().eq('id',goal.id);if(error)return toast(error.message,'error');w.remove();await loadGoals();render()};w.querySelector('#f').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),payload={household_id:state.household.id,title:fd.get('title').trim(),notes:fd.get('notes').trim()||null,box_id:fd.get('box')||null,target_amount:fd.get('target')?Number(fd.get('target')):null,created_by:state.session.user.id};let error;if(goal)({error}=await supabase.from('goals').update(payload).eq('id',goal.id));else({error}=await supabase.from('goals').insert(payload));if(error)return toast(error.message,'error');w.remove();await loadGoals();render()}})}
function openRecurring(){modal('Novo gasto fixo',`<form id="f" class="form-grid"><div class="field"><label>Descrição</label><input class="input" name="description" required></div><div class="field"><label>Valor</label><input class="input" name="amount" type="number" step="0.01" min="0.01" required></div><div class="field"><label>Começa em</label><input class="input" name="start" type="month" value="${state.selectedMonth.slice(0,7)}" required></div><div class="field"><label>Vai até (opcional)</label><input class="input" name="end" type="month"><div class="row-sub">Vazio = sem data final.</div></div><div class="modal-actions"><button class="btn ghost" type="button" data-cancel>Cancelar</button><button class="btn primary">Criar gasto fixo</button></div></form>`,w=>{w.querySelector('[data-cancel]').onclick=()=>w.remove();w.querySelector('#f').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const{error}=await supabase.rpc('create_recurring_expense',{p_household_id:state.household.id,p_description:fd.get('description').trim(),p_amount:Number(fd.get('amount')),p_start_month:`${fd.get('start')}-01`,p_end_month:fd.get('end')?`${fd.get('end')}-01`:null});if(error)return toast(error.message,'error');w.remove();await refresh();render()}})}

async function loadProfile(){const{data}=await supabase.from('profiles').select('*').eq('id',state.session.user.id).maybeSingle();state.profile=data}
async function loadHousehold(){const{data:member,error}=await supabase.from('household_members').select('household_id').eq('user_id',state.session.user.id).maybeSingle();if(error)throw error;if(!member){state.household=null;return}const{data,error:h}=await supabase.from('households').select('*').eq('id',member.household_id).single();if(h)throw h;state.household=data}
async function loadTransactions(){if(!state.household)return;const year=Number(state.selectedMonth.slice(0,4));const{data,error}=await supabase.from('transactions').select('*').eq('household_id',state.household.id).gte('month',`${year-1}-01-01`).lte('month',`${year+1}-12-01`).order('month',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;state.transactions=data||[]}
async function loadBoxes(){if(!state.household)return;const[{data:boxes,error:e1},{data:balances,error:e2}]=await Promise.all([supabase.from('boxes').select('*').eq('household_id',state.household.id).eq('is_archived',false).order('created_at'),supabase.from('box_balances').select('*').eq('household_id',state.household.id)]);if(e1)throw e1;if(e2)throw e2;state.boxes=boxes||[];state.boxBalances=balances||[]}
async function loadGoals(){if(!state.household)return;const{data,error}=await supabase.from('goals').select('*').eq('household_id',state.household.id).order('sort_order').order('created_at');if(error)throw error;state.goals=data||[]}
async function loadSummary(){if(!state.household)return;const{data,error}=await supabase.from('monthly_summary').select('*').eq('household_id',state.household.id).order('month');if(error)throw error;state.monthlySummary=data||[]}
async function ensureRecurring(){if(!state.household)return;const{error}=await supabase.rpc('ensure_recurring_for_month',{p_household_id:state.household.id,p_month:state.selectedMonth});if(error)console.warn(error)}
async function refresh(){await Promise.all([loadTransactions(),loadBoxes(),loadGoals(),loadSummary()])}
async function loadAll(){state.loading=true;render();try{await loadProfile();await loadHousehold();if(state.household){await ensureRecurring();await refresh()}}catch(err){console.error(err);toast(err.message||'Falha ao carregar dados.','error')}finally{state.loading=false;render()}}
async function init(){if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));const{data:{session}}=await supabase.auth.getSession();state.session=session;supabase.auth.onAuthStateChange(async(_event,s)=>{state.session=s;if(s)await loadAll();else{state.profile=null;state.household=null;state.loading=false;render()}});if(session)await loadAll();else{state.loading=false;render()}}
init();
